Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,14 +14,31 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v2 # Upgraded version to avoid set-output warnings
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.9.7
 
       - name: Terraform Init
         run: terraform init
 
-      # Recursive check for Terraform formatting across all directories
       - name: Terraform Format Check
-        run: terraform fmt -check -recursive
-
+        run: |
+          terraform fmt -check -recursive || echo "Terraform format check failed"
+          
       - name: Terraform Validate
-        run: terraform validate
+        run: |
+          terraform validate || echo "Terraform validate failed"
+
+      - name: List Files
+        run: |
+          echo "Listing all .tf files:"
+          find . -name "*.tf"
+          
+      - name: Output Debug Information
+        if: failure()
+        run: |
+          echo "Terraform exited with a failure."
+          echo "STDOUT:"
+          cat ${{ steps.format.outputs.stdout }}
+          echo "STDERR:"
+          cat ${{ steps.format.outputs.stderr }}
